----------------------------------- PRIVILEGIOS
GRANT CONNECT,CREATE PROCEDURE,CREATE TRIGGER,CREATE VIEW,CREATE MATERIALIZED VIEW TO ROL_DESARROLLADOR;
GRANT CONNECT TO ROL_CONSULTOR;

GRANT ROL_DESARROLLADOR TO DESARROLLADOR_1;
GRANT CREATE SEQUENCE, ROL_DESARROLLADOR TO DESARROLLADOR_2;

GRANT ROL_CONSULTOR TO CONSULTOR_1;
GRANT ROL_CONSULTOR TO CONSULTOR_2;
GRANT ROL_CONSULTOR TO CONSULTOR_3;

