--*************** USUARIO ADMINISTRADOR ***************--
-- USER SQL
CREATE USER "ADMINISTRADOR" IDENTIFIED BY "PROYECTO_semestral_01"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- ROLES
GRANT CONNECT, RESOURCE TO "ADMINISTRADOR"

-- SYSTEM PRIVILEGES
GRANT CREATE VIEW TO "ADMINISTRADOR" ;
GRANT UNLIMITED TABLESPACE TO "ADMINISTRADOR" ;

ALTER USER "ADMINISTRADOR"
DEFAULT TABLESPACE "SYSTEM"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS

-- ROLES
ALTER USER "ADMINISTRADOR" DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES
GRANT CREATE PUBLIC SYNONYM TO "ADMINISTRADOR" ;
GRANT CREATE ANY SYNONYM TO "ADMINISTRADOR" ;
GRANT DROP ANY SYNONYM TO "ADMINISTRADOR" ;

--------------------------------------------------------

-- crear conexiones de usuarios DESARROLLADOR
CREATE USER "DESARROLLADOR_1" IDENTIFIED BY "PROYECTO_semestral_DES1_01"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

CREATE USER "DESARROLLADOR_2" IDENTIFIED BY "PROYECTO_semestraL_DES2_l01"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- crear conexiones de usuarios CONSULTOR
CREATE USER "CONSULTOR_1" IDENTIFIED BY "PROYECTO_semestral_con1_l01"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

CREATE USER "CONSULTOR_2" IDENTIFIED BY "PROYECTO_semestral_con2_l01"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

CREATE USER "CONSULTOR_3" IDENTIFIED BY "PROYECTO_semestral_con3_l01"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

